"""add_started_at

Revision ID: 03f7a6b914a3
Revises: be228ed1304e
Create Date: 2026-07-16 14:36:39.008984

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '03f7a6b914a3'
down_revision = 'be228ed1304e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_assignments', 'started_at')
    # ### end Alembic commands ###

