"""add seed column to quiz_questions

Revision ID: 4e5b6bf77b75
Revises: 9d263add4300
Create Date: 2026-07-10 09:19:36.720523

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4e5b6bf77b75'
down_revision = '9d263add4300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('seed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'seed')
    # ### end Alembic commands ###

