"""Add parent_id to users

Revision ID: 82d9dbfdc692
Revises: 0011_subscription_plans
Create Date: 2026-03-11 15:46:30.025531

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d9dbfdc692'
down_revision = '0011_subscription_plans'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_id')
    # ### end Alembic commands ###
