"""add_quiz_assignment_fields

Revision ID: a99c1bfe737f
Revises: 4e5b6bf77b75
Create Date: 2026-07-14 09:43:28.661616

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a99c1bfe737f'
down_revision = '4e5b6bf77b75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_assignments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_assignments', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    op.add_column('quiz_assignments', sa.Column('question_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_assignments', 'question_results')
    op.drop_column('quiz_assignments', 'time_spent_seconds')
    op.drop_column('quiz_assignments', 'score')
    op.drop_column('quiz_assignments', 'completed_at')
    # ### end Alembic commands ###

