"""Add quiz models

Revision ID: ae79a27c58a9
Revises: c8f4e5b9a2d1
Create Date: 2026-04-15 20:01:01.735560

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ae79a27c58a9'
down_revision = 'c8f4e5b9a2d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.Enum('FIXED', 'RANDOMIZED', name='quiz_question_order'), nullable=False),
    sa.Column('result_visibility', sa.Enum('ALWAYS', 'SCORE_ONLY', 'HIDDEN', name='quiz_result_visibility'), nullable=False),
    sa.Column('end_type', sa.Enum('MANUAL', 'SCHEDULED', name='quiz_end_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_teacher_id'), 'quizzes', ['teacher_id'], unique=False)
    op.create_table('quiz_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_assignments_classroom_id'), 'quiz_assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_quiz_id'), 'quiz_assignments', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_assignments_student_id'), 'quiz_assignments', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_question_id'), 'quiz_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.drop_index(op.f('ix_assignment_status_student_assignment'), table_name='assignment_status')
    op.drop_index(op.f('ix_assignments_classroom_created_at'), table_name='assignments')
    op.drop_index(op.f('ix_practice_attempts_session_answered_at'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_session_question_not_null'), table_name='practice_attempts', postgresql_where='(question_id IS NOT NULL)')
    op.drop_index(op.f('ix_practice_attempts_user_skill_answered_at'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_sessions_active_lookup'), table_name='practice_sessions', postgresql_where='(finished_at IS NULL)')
    op.drop_index(op.f('ix_progress_snapshots_user_last_practiced_at'), table_name='progress_snapshots')
    op.drop_index(op.f('ix_questions_skill_level_id'), table_name='questions')
    op.drop_index(op.f('ix_skills_published_subject_grade_code'), table_name='skills')
    op.drop_index(op.f('ix_topics_published_order_id'), table_name='topics')
    op.drop_index(op.f('ix_users_parent_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_parent_id'), 'users', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topics_published_order_id'), 'topics', ['is_published', 'order', 'id'], unique=False)
    op.create_index(op.f('ix_skills_published_subject_grade_code'), 'skills', ['is_published', 'subject_id', 'grade_id', 'code'], unique=False)
    op.create_index(op.f('ix_questions_skill_level_id'), 'questions', ['skill_id', 'level', 'id'], unique=False)
    op.create_index(op.f('ix_progress_snapshots_user_last_practiced_at'), 'progress_snapshots', ['user_id', 'last_practiced_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_active_lookup'), 'practice_sessions', ['user_id', 'skill_id', 'last_activity_at'], unique=False, postgresql_where='(finished_at IS NULL)')
    op.create_index(op.f('ix_practice_attempts_user_skill_answered_at'), 'practice_attempts', ['user_id', 'skill_id', 'answered_at'], unique=False)
    op.create_index(op.f('ix_practice_attempts_session_question_not_null'), 'practice_attempts', ['session_id', 'question_id'], unique=False, postgresql_where='(question_id IS NOT NULL)')
    op.create_index(op.f('ix_practice_attempts_session_answered_at'), 'practice_attempts', ['session_id', 'answered_at'], unique=False)
    op.create_index(op.f('ix_assignments_classroom_created_at'), 'assignments', ['classroom_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assignment_status_student_assignment'), 'assignment_status', ['student_id', 'assignment_id'], unique=False)
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_question_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_assignments_student_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_quiz_id'), table_name='quiz_assignments')
    op.drop_index(op.f('ix_quiz_assignments_classroom_id'), table_name='quiz_assignments')
    op.drop_table('quiz_assignments')
    op.drop_index(op.f('ix_quizzes_teacher_id'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###

