"""add parent_id to topics

Revision ID: 6e10a3659ce6
Revises: 0010_grade_label_nn
Create Date: 2026-03-01 21:39:31.557334

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6e10a3659ce6'
down_revision = '0010_grade_label_nn'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_topics_parent_id'), 'topics', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'topics', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_parent_id'), table_name='topics')
    op.drop_column('topics', 'parent_id')
    # ### end Alembic commands ###

