"""add gamification models

Revision ID: 793dc8fc4bb5
Revises: ae79a27c58a9
Create Date: 2026-07-03 10:19:02.962029

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '793dc8fc4bb5'
down_revision = 'ae79a27c58a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('criteria_key', sa.String(length=100), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria_key')
    )
    op.create_table('daily_missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mission_type', sa.String(length=50), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('asset_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_items_user_id'), 'user_items', ['user_id'], unique=False)
    op.create_table('user_missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['daily_missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('last_study_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_study_date')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'coins')
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_table('user_missions')
    op.drop_index(op.f('ix_user_items_user_id'), table_name='user_items')
    op.drop_table('user_items')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('shop_items')
    op.drop_table('daily_missions')
    op.drop_table('achievements')
    # ### end Alembic commands ###

