"""add_teacher_id_to_user

Revision ID: 7f03a32587df
Revises: 82d9dbfdc692
Create Date: 2026-03-12 16:54:30.199015

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7f03a32587df'
down_revision = '82d9dbfdc692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'teacher_id')
    # ### end Alembic commands ###

