"""make_question_id_nullable_for_generators

Revision ID: b9d78e3eeff1
Revises: 0004_generator_code
Create Date: 2026-01-21 15:31:28.613891

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b9d78e3eeff1'
down_revision = '0004_generator_code'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем UniqueConstraint, так как question_id теперь может быть NULL для генераторов
    op.drop_constraint('uq_attempt_session_question', 'practice_attempts', type_='unique')
    op.alter_column('practice_attempts', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.alter_column('practice_attempts', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # Восстанавливаем UniqueConstraint (если его еще нет)
    try:
        op.create_unique_constraint('uq_attempt_session_question', 'practice_attempts', ['session_id', 'question_id'])
    except Exception:
        # Constraint уже существует, пропускаем
        pass
    # ### end Alembic commands ###

